### ISSUE TITLE
FYI: this action is no longer functional. zstd 1.4.7 is not there...

### ISSUE THREAD

**Issue by uditrugman** [GuillaumeFalourd/setup-rsync#1]

**Comment by GuillaumeFalourd** [comment]
Hi @uditrugman , how are you doing? Thank you for opening this issue! 👍🏼 

For what I checked here, it seems the action isn't working on windows anymore, but it is on ubuntu e macos.
- [windows](https://github.com/GuillaumeFalourd/setup-rsync/actions/runs/3176048984/jobs/5174874651)
- [ubuntu](https://github.com/GuillaumeFalourd/setup-rsync/actions/runs/3176048592/jobs/5174873667)
- [macos](https://github.com/GuillaumeFalourd/setup-rsync/actions/runs/3176048063/jobs/5174872700)

I'll look for a workaround on windows. Do you know about any alternative to `zstd`?

**Comment by uditrugman** [comment]
Hi,

Thanks for fixing this!

I’m not aware of any alternative. I’ve actually just learned that zstd exists :)
